spring:
  config:
    import:
      - classpath:config-file/application-common.yml
      - classpath:config-file/application-db.yml
      - classpath:config-file/application-json.yml

  application:
    name: YoumI
  profiles:
    active:
      - local
    group:
      local:
        - db-local
        - json-local
      oracle:
        - db-oracle
        - json-oracle
      prod:
    include:
      - db
      - common